"use client";

import type React from "react";
import { createContext, useContext, useState, useEffect, useCallback } from "react";

export type Language = "en" | "ar";

type Dict = Record<string, string>;

const en: Dict = {
  "brand.name": "AURIC",
  "brand.tagline": "Sound, Refined.",
  "announce.1": "Free worldwide shipping on orders over $200",
  "announce.2": "2-year warranty on every AURIC ONE",
  "announce.3": "30-day returns, no questions asked",
  "nav.home": "Home",
  "nav.product": "The ONE",
  "nav.reviews": "Reviews",
  "nav.accessories": "Accessories",
  "nav.support": "Support",
  "nav.about": "About",
  "nav.account": "Account",
  "nav.search": "Search",
  "nav.cart": "Cart",
  "nav.wishlist": "Wishlist",
  "nav.menu": "Menu",
  "nav.close": "Close",
  "nav.shop": "Shop",
  "nav.company": "Company",
  "nav.help": "Help",
  "nav.follow": "Follow",
  "nav.subscribe": "Subscribe",
  "nav.dashboard": "Dashboard",
  "nav.orders": "Orders",
  "nav.addresses": "Addresses",
  "nav.payments": "Payment methods",
  "nav.wishlistNav": "Wishlist",
  "nav.profile": "Profile",
  "nav.security": "Security",
  "nav.notifications": "Notifications",
  "nav.signout": "Sign out",
  "nav.signin": "Sign in",
  "hero.eyebrow": "Reference Series",
  "hero.title": "Sound, Refined.",
  "hero.subtitle": "The AURIC ONE",
  "hero.description": "Reference-grade wireless headphones with 40mm beryllium drivers, adaptive ANC, 60-hour battery, and lossless Hi-Res audio.",
  "hero.cta.shop": "Shop the ONE",
  "hero.cta.reviews": "Read reviews",
  "hero.cta.explore": "Explore the sound",
  "hero.price.from": "From",
  "hero.save": "Save $150",
  "showcase.eyebrow": "Engineered, not assembled",
  "showcase.title": "Three years in the making",
  "showcase.body": "Every AURIC ONE is the product of relentless engineering — beryllium drivers machined to 0.5 microns, a Class-A discrete amplifier, eight microphones reading your environment 50,000 times per second. Nothing is left to chance.",
  "features.eyebrow": "What's inside",
  "features.title": "Four reasons it sounds like this",
  "features.subtitle": "Each subsystem was built from first principles. No borrowed platforms. No off-the-shelf DSP profiles.",
  "specs.eyebrow": "Technical",
  "specs.title": "Full specifications",
  "specs.subtitle": "Measured, not estimated. Every spec is verified on every unit that ships.",
  "comparison.eyebrow": "How it compares",
  "comparison.title": "AURIC ONE vs the competition",
  "comparison.subtitle": "Specs that matter, side by side. We welcome the comparison.",
  "comparison.auric": "AURIC ONE",
  "comparison.other": "Leading competitor",
  "lifestyle.eyebrow": "Built for the long session",
  "lifestyle.title": "Eight hours, weightless",
  "lifestyle.body": "A floating suspension headband and protein-leather earcups distribute weight so evenly that marathon sessions disappear. The AURIC ONE doesn't ask you to take breaks — it removes the reason you needed them.",
  "gallery.eyebrow": "In detail",
  "gallery.title": "Every angle, considered",
  "gallery.subtitle": "Aircraft-grade aluminum. Hand-stitched protein leather. Machined to tolerances you can feel.",
  "reviews.eyebrow": "Verified buyers",
  "reviews.title": "What owners say",
  "reviews.subtitle": "4.9 average across 2,847 verified reviews. We don't curate — we publish them all.",
  "reviews.based": "based on",
  "reviews.reviews": "reviews",
  "reviews.verified": "Verified buyer",
  "reviews.helpful": "Helpful",
  "reviews.write": "Write a review",
  "reviews.yourName": "Your name",
  "reviews.yourTitle": "Review title",
  "reviews.yourBody": "Your review",
  "reviews.rating": "Rating",
  "reviews.submit": "Submit review",
  "reviews.submitting": "Submitting...",
  "reviews.verifiedOnly": "Only verified buyers can leave reviews.",
  "reviews.distribution": "Rating breakdown",
  "reviews.all": "All reviews",
  "reviews.5star": "5 star",
  "reviews.4star": "4 star",
  "reviews.3star": "3 star",
  "reviews.2star": "2 star",
  "reviews.1star": "1 star",
  "reviews.withPhotos": "With photos",
  "reviews.mostHelpful": "Most helpful",
  "reviews.mostRecent": "Most recent",
  "reviews.highestRated": "Highest rated",
  "reviews.lowestRated": "Lowest rated",
  "reviews.sortBy": "Sort by",
  "reviews.filterBy": "Filter by",
  "reviews.helpfulCount": "found this helpful",
  "testimonials.eyebrow": "Trusted by professionals",
  "testimonials.title": "When the room is the studio",
  "testimonials.subtitle": "Mastering engineers, producers, and composers who've put the AURIC ONE in their daily rotation.",
  "faq.eyebrow": "Common questions",
  "faq.title": "Everything you'd want to know",
  "faq.subtitle": "Can't find what you're looking for? Our team replies within 4 hours.",
  "faq.contact": "Contact support",
  "newsletter.eyebrow": "Stay in tune",
  "newsletter.title": "First listen to what's next",
  "newsletter.subtitle": "Product launches, firmware updates, and the occasional engineering deep-dive. No spam, ever. Unsubscribe in one click.",
  "newsletter.placeholder": "your@email.com",
  "newsletter.subscribe": "Subscribe",
  "newsletter.privacy": "We respect your privacy. Read our Privacy Policy.",
  "trust.shipping": "Free worldwide shipping",
  "trust.returns": "30-day returns",
  "trust.warranty": "2-year warranty",
  "trust.secure": "Secure checkout",
  "product.inStock": "In stock",
  "product.lowStock": "Only {n} left",
  "product.outOfStock": "Out of stock",
  "product.color": "Color",
  "product.quantity": "Quantity",
  "product.addToCart": "Add to cart",
  "product.buyNow": "Buy now",
  "product.estimatedDelivery": "Estimated delivery",
  "product.deliveryValue": "Jun 26 – Jun 28",
  "product.shippingValue": "Free worldwide",
  "product.warranty": "Warranty",
  "product.warrantyValue": "2 years",
  "product.returns": "Returns",
  "product.returnsValue": "30 days, free returns",
  "product.share": "Share",
  "product.compare": "Compare",
  "product.wishlist": "Add to wishlist",
  "product.specifications": "Specifications",
  "product.inTheBox": "In the box",
  "product.description": "Description",
  "product.reviews": "Reviews",
  "product.related": "You may also like",
  "product.accessories": "Accessories",
  "product.fbt": "Frequently bought together",
  "product.fbtSave": "Save {n} when bought together",
  "product.recentlyViewed": "Recently viewed",
  "product.addBundle": "Add bundle to cart",
  "product.totalBundle": "Bundle total",
  "product.features": "Features",
  "product.gallery": "Gallery",
  "product.zoom": "Hover to zoom. Click to expand.",
  "product.expand": "Expand",
  "product.fullscreen": "View fullscreen",
  "product.downloadSpecSheet": "Download spec sheet (PDF)",
  "product.downloadManual": "Download user manual (PDF)",
  "product.included": "What's included",
  "product.cable": "USB-C to USB-C cable (1m)",
  "product.case": "Premium travel case",
  "product.adapter": "3.5mm to USB-C adapter",
  "product.manual": "Quick start guide",
  "cart.title": "Your cart",
  "cart.empty": "Your cart is empty",
  "cart.emptySubtitle": "When you find something you love, it'll show up here.",
  "cart.continueShopping": "Continue shopping",
  "cart.subtotal": "Subtotal",
  "cart.estimatedShipping": "Estimated shipping",
  "cart.free": "Free",
  "cart.estimatedTax": "Estimated tax",
  "cart.total": "Total",
  "cart.checkout": "Proceed to checkout",
  "cart.coupon": "Coupon code",
  "cart.apply": "Apply",
  "cart.couponApplied": "Coupon applied",
  "cart.couponInvalid": "Invalid coupon",
  "cart.giftWrap": "Add gift wrap (+$9)",
  "cart.giftWrapAdded": "Gift wrap added",
  "cart.orderNotes": "Order notes",
  "cart.orderNotesPlaceholder": "Special instructions for the seller...",
  "cart.saveForLater": "Save for later",
  "cart.remove": "Remove",
  "cart.move": "Move to cart",
  "cart.qty": "Qty",
  "cart.recommendations": "You may also like",
  "cart.shippingCalculator": "Shipping calculator",
  "cart.calculate": "Calculate",
  "cart.zip": "ZIP / Postal code",
  "cart.country": "Country",
  "cart.empty.look": "Look around",
  "cart.saved": "Saved for later",
  "cart.savedEmpty": "No saved items yet",
  "cart.savedCount": "{n} items saved",
  "cart.youMightLike": "You might like these",
  "cart.freeShipProgress": "You're {n} away from free shipping",
  "cart.freeShipUnlocked": "You've unlocked free shipping",
  "cart.freeShipThreshold": "Free shipping at $200",
  "cartDrawer.title": "Your bag",
  "cartDrawer.added": "Added to your bag",
  "cartDrawer.checkout": "Checkout",
  "cartDrawer.viewCart": "View full cart",
  "cartDrawer.empty": "Your bag is empty",
  "cartDrawer.emptySubtitle": "Start with the AURIC ONE.",
  "cartDrawer.subtotal": "Subtotal",
  "cartDrawer.shippingNote": "Shipping & taxes calculated at checkout",
  "checkout.title": "Checkout",
  "checkout.step.shipping": "Shipping",
  "checkout.step.billing": "Billing",
  "checkout.step.payment": "Payment",
  "checkout.step.review": "Review",
  "checkout.contact": "Contact information",
  "checkout.email": "Email address",
  "checkout.phone": "Phone number",
  "checkout.shippingAddress": "Shipping address",
  "checkout.firstName": "First name",
  "checkout.lastName": "Last name",
  "checkout.address1": "Address line 1",
  "checkout.address2": "Address line 2 (optional)",
  "checkout.city": "City",
  "checkout.state": "State / Province",
  "checkout.postal": "Postal code",
  "checkout.country": "Country",
  "checkout.shippingMethod": "Shipping method",
  "checkout.shipping.standard": "Standard — 2–5 days",
  "checkout.shipping.express": "Express — 1–2 days",
  "checkout.shipping.standardPrice": "Free",
  "checkout.shipping.expressPrice": "$24",
  "checkout.billingSame": "Billing address same as shipping",
  "checkout.billingAddress": "Billing address",
  "checkout.paymentMethod": "Payment method",
  "checkout.payment.card": "Credit / debit card",
  "checkout.payment.paypal": "PayPal",
  "checkout.payment.applePay": "Apple Pay",
  "checkout.payment.klarna": "Klarna — 4 interest-free payments",
  "checkout.cardNumber": "Card number",
  "checkout.cardName": "Name on card",
  "checkout.cardExpiry": "MM / YY",
  "checkout.cardCvc": "CVC",
  "checkout.review.order": "Order review",
  "checkout.review.items": "{n} items",
  "checkout.review.placeOrder": "Place order",
  "checkout.processing": "Processing payment...",
  "checkout.securePayment": "Secure, encrypted payment",
  "checkout.summary": "Order summary",
  "checkout.continue": "Continue",
  "checkout.back": "Back",
  "checkout.applyCoupon": "Apply coupon",
  "checkout.coupon": "Coupon code",
  "checkout.orderNotes": "Order notes (optional)",
  "checkout.giftWrap": "Add gift wrap",
  "checkout.subscribeMarketing": "Email me about AURIC launches",
  "checkout.terms": "I agree to the Terms of Service and Privacy Policy",
  "orderSuccess.title": "Order confirmed",
  "orderSuccess.body": "Thank you. Your AURIC ONE is on its way. We've emailed a confirmation and tracking link to {email}.",
  "orderSuccess.orderNumber": "Order number",
  "orderSuccess.trackOrder": "Track your order",
  "orderSuccess.continueShopping": "Continue shopping",
  "orderSuccess.estimatedDelivery": "Estimated delivery",
  "orderSuccess.nowVerified": "You're now a verified buyer — you can leave reviews!",
  "orderFailed.title": "Payment failed",
  "orderFailed.body": "Your payment could not be processed. No charges were made. Please try again or use a different payment method.",
  "orderFailed.retry": "Try again",
  "orderFailed.contact": "Contact support",
  "orderCancelled.title": "Order cancelled",
  "orderCancelled.body": "Your order has been cancelled. No charges were made.",
  "orderCancelled.continue": "Continue shopping",
  "track.title": "Track your order",
  "track.subtitle": "Enter your order number and the email used at checkout.",
  "track.orderNumber": "Order number",
  "track.email": "Email address",
  "track.track": "Track order",
  "track.found": "Order found",
  "track.notFound": "Order not found. Check your details and try again.",
  "track.status": "Status",
  "track.estimatedDelivery": "Estimated delivery",
  "track.carrier": "Carrier",
  "track.timeline": "Shipment timeline",
  "wishlist.title": "Your wishlist",
  "wishlist.subtitle": "Items you've saved for later",
  "wishlist.empty": "Your wishlist is empty",
  "wishlist.emptySubtitle": "Tap the heart on any product to save it here.",
  "wishlist.moveToCart": "Move to cart",
  "wishlist.count": "{n} items",
  "compare.title": "Compare products",
  "compare.subtitle": "Side-by-side comparison of {n} products",
  "compare.empty": "Nothing to compare yet",
  "compare.emptySubtitle": "Add products to compare using the compare icon.",
  "compare.add": "Add to compare",
  "compare.remove": "Remove",
  "compare.maxReached": "Maximum 4 products can be compared",
  "compare.addToCart": "Add to cart",
  "search.title": "Search",
  "search.placeholder": "Search AURIC...",
  "search.trending": "Trending searches",
  "search.recent": "Recent searches",
  "search.popular": "Popular categories",
  "search.results": "Search results for \"{q}\"",
  "search.noResults": "No results for \"{q}\"",
  "search.noResultsSubtitle": "Try different keywords or browse our products.",
  "search.clear": "Clear",
  "search.clearAll": "Clear all",
  "search.count": "{n} results found",
  "search.viewAll": "View all results",
  "search.suggestions": "Suggestions",
  "search.filters": "Filters",
  "search.sortBy": "Sort by",
  "search.sort.relevance": "Relevance",
  "search.sort.priceAsc": "Price: Low to High",
  "search.sort.priceDesc": "Price: High to Low",
  "search.sort.rating": "Highest rated",
  "search.sort.newest": "Newest",
  "account.title": "My account",
  "account.welcome": "Welcome back, {name}",
  "account.recentOrders": "Recent orders",
  "account.viewAll": "View all",
  "account.noOrders": "No orders yet",
  "account.noOrdersSubtitle": "When you place an order, it'll appear here.",
  "account.savedAddresses": "Saved addresses",
  "account.defaultAddress": "Default",
  "account.addAddress": "Add address",
  "account.editAddress": "Edit",
  "account.paymentMethods": "Payment methods",
  "account.addPayment": "Add payment method",
  "account.default": "Default",
  "account.profile": "Profile",
  "account.profile.firstName": "First name",
  "account.profile.lastName": "Last name",
  "account.profile.email": "Email",
  "account.profile.phone": "Phone",
  "account.profile.save": "Save changes",
  "account.security": "Security",
  "account.security.password": "Password",
  "account.security.changePassword": "Change password",
  "account.security.currentPassword": "Current password",
  "account.security.newPassword": "New password",
  "account.security.confirmPassword": "Confirm new password",
  "account.security.twoFactor": "Two-factor authentication",
  "account.security.twoFactorDesc": "Add an extra layer of security with TOTP",
  "account.security.sessions": "Active sessions",
  "account.security.signOutAll": "Sign out of all sessions",
  "account.notifications": "Notifications",
  "account.notif.orders": "Order updates",
  "account.notif.marketing": "Product launches",
  "account.notif.reviews": "Review replies",
  "account.notif.security": "Security alerts",
  "account.signout": "Sign out",
  "account.orderId": "Order",
  "account.orderDate": "Date",
  "account.orderStatus": "Status",
  "account.orderTotal": "Total",
  "account.orderActions": "Actions",
  "account.viewOrder": "View",
  "account.invoice": "Invoice",
  "account.buyAgain": "Buy again",
  "account.track": "Track",
  "account.return": "Return",
  "account.cancelOrder": "Cancel",
  "account.status.delivered": "Delivered",
  "account.status.shipped": "Shipped",
  "account.status.processing": "Processing",
  "account.status.cancelled": "Cancelled",
  "account.status.returned": "Returned",
  "invoice.title": "Invoice",
  "invoice.number": "Invoice number",
  "invoice.date": "Invoice date",
  "invoice.due": "Due date",
  "invoice.billTo": "Bill to",
  "invoice.shipTo": "Ship to",
  "invoice.item": "Item",
  "invoice.qty": "Qty",
  "invoice.price": "Price",
  "invoice.total": "Total",
  "invoice.subtotal": "Subtotal",
  "invoice.shipping": "Shipping",
  "invoice.tax": "Tax",
  "invoice.grandTotal": "Grand total",
  "invoice.download": "Download PDF",
  "invoice.print": "Print",
  "invoice.thanks": "Thank you for your business.",
  "auth.signIn": "Sign in",
  "auth.signUp": "Create account",
  "auth.forgot": "Forgot password?",
  "auth.reset": "Reset password",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.confirmPassword": "Confirm password",
  "auth.name": "Full name",
  "auth.signInButton": "Sign in",
  "auth.signUpButton": "Create account",
  "auth.resetButton": "Send reset link",
  "auth.resetSent": "If an account exists for {email}, a reset link has been sent.",
  "auth.noAccount": "Don't have an account?",
  "auth.haveAccount": "Already have an account?",
  "auth.signInWith": "or continue with",
  "auth.terms": "By creating an account, you agree to our Terms and Privacy Policy.",
  "auth.welcomeBack": "Welcome back",
  "auth.createAccount": "Join AURIC",
  "auth.createAccountSubtitle": "Faster checkout, order history, and exclusive launches.",
  "auth.signInSubtitle": "Sign in to your AURIC account",
  "auth.forgotSubtitle": "Enter your email and we'll send a reset link.",
  "auth.resetSubtitle": "Enter your new password",
  "auth.newPassword": "New password",
  "auth.updatePassword": "Update password",
  "auth.passwordUpdated": "Password updated. You can now sign in.",
  "auth.rememberMe": "Remember me",
  "policy.shipping": "Shipping Policy",
  "policy.returns": "Returns & Exchanges",
  "policy.warranty": "Warranty",
  "policy.privacy": "Privacy Policy",
  "policy.terms": "Terms of Service",
  "policy.refund": "Refund Policy",
  "policy.lastUpdated": "Last updated",
  "policy.tableOfContents": "On this page",
  "about.eyebrow": "Our story",
  "about.title": "We started in a Copenhagen workshop",
  "about.subtitle": "AURIC was founded in 2021 by three former Bang & Olufsen engineers who believed wireless audio had stopped short of its potential.",
  "about.founded": "Founded",
  "about.headquarters": "Headquarters",
  "about.team": "Team",
  "about.mission": "Mission",
  "about.vision": "Vision",
  "about.cta": "Explore the AURIC ONE",
  "contact.title": "Get in touch",
  "contact.subtitle": "Our team replies within 4 hours, Monday through Friday.",
  "contact.name": "Your name",
  "contact.email": "Your email",
  "contact.subject": "Subject",
  "contact.message": "Message",
  "contact.send": "Send message",
  "contact.sent": "Message sent. We'll reply within 4 hours.",
  "contact.emailUs": "Email us",
  "contact.callUs": "Call us",
  "contact.hours": "Hours",
  "contact.visitUs": "Visit us",
  "support.title": "Help center",
  "support.subtitle": "Find answers, browse articles, or reach out to our team.",
  "support.search": "Search help articles...",
  "support.browse": "Browse by category",
  "support.popular": "Popular articles",
  "support.contactSupport": "Contact support",
  "support.openTicket": "Open a support ticket",
  "support.ticketSubject": "Subject",
  "support.ticketOrder": "Order number (optional)",
  "support.ticketCategory": "Category",
  "support.ticketPriority": "Priority",
  "support.ticketMessage": "Describe your issue",
  "support.ticketSubmit": "Submit ticket",
  "support.ticketSubmitted": "Ticket #{n} created. We'll reply within 4 hours.",
  "error.404.title": "Page not found",
  "error.404.body": "The page you're looking for doesn't exist or has moved.",
  "error.500.title": "Something went wrong",
  "error.500.body": "We're already on it. Try again in a moment.",
  "error.offline.title": "You're offline",
  "error.offline.body": "Check your connection and try again.",
  "error.maintenance.title": "We'll be right back",
  "error.maintenance.body": "AURIC is undergoing scheduled maintenance. Back shortly.",
  "error.comingSoon.title": "Coming soon",
  "error.comingSoon.body": "Something new is on the way. Be the first to know.",
  "error.retry": "Try again",
  "error.home": "Back to home",
  "footer.tagline": "Sound, refined. Built in Copenhagen.",
  "footer.shop": "Shop",
  "footer.company": "Company",
  "footer.help": "Help",
  "footer.follow": "Follow",
  "footer.subscribe": "Subscribe",
  "footer.subscribeBody": "First listen to what's next. No spam.",
  "footer.rights": "All rights reserved.",
  "footer.terms": "Terms",
  "footer.privacy": "Privacy",
  "footer.cookies": "Cookies",
  "footer.accessibility": "Accessibility",
  "footer.poweredBy": "Engineered in Copenhagen, shipped worldwide.",
  "common.loading": "Loading...",
  "common.saving": "Saving...",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.close": "Close",
  "common.continue": "Continue",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.apply": "Apply",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.sort": "Sort",
  "common.viewAll": "View all",
  "common.viewMore": "View more",
  "common.viewLess": "View less",
  "common.addToCart": "Add to cart",
  "common.buyNow": "Buy now",
  "common.outOfStock": "Out of stock",
  "common.inStock": "In stock",
  "common.new": "New",
  "common.sale": "Sale",
  "common.bestseller": "Bestseller",
  "common.limited": "Limited",
  "common.free": "Free",
  "common.optional": "optional",
  "common.required": "required",
  "common.currency": "$",
  "common.select": "Select...",
  "common.yes": "Yes",
  "common.no": "No",
  "common.copied": "Copied!",
  "common.share": "Share",
};

const ar: Dict = {
  "brand.name": "أوريك",
  "brand.tagline": "الصوت، بكل تفاصيله.",
  "announce.1": "شحن عالمي مجاني للطلبات فوق 200 دولار",
  "announce.2": "ضمان سنتين على كل سماعة أوريك ون",
  "announce.3": "إرجاع خلال 30 يوماً، دون أسئلة",
  "nav.home": "الرئيسية",
  "nav.product": "أوريك ون",
  "nav.reviews": "التقييمات",
  "nav.accessories": "الملحقات",
  "nav.support": "الدعم",
  "nav.about": "من نحن",
  "nav.account": "الحساب",
  "nav.search": "بحث",
  "nav.cart": "السلة",
  "nav.wishlist": "المفضلة",
  "nav.menu": "القائمة",
  "nav.close": "إغلاق",
  "nav.shop": "تسوق",
  "nav.company": "الشركة",
  "nav.help": "المساعدة",
  "nav.follow": "تابعنا",
  "nav.subscribe": "اشترك",
  "nav.dashboard": "لوحة التحكم",
  "nav.orders": "الطلبات",
  "nav.addresses": "العناوين",
  "nav.payments": "طرق الدفع",
  "nav.wishlistNav": "المفضلة",
  "nav.profile": "الملف الشخصي",
  "nav.security": "الأمان",
  "nav.notifications": "الإشعارات",
  "nav.signout": "تسجيل الخروج",
  "nav.signin": "تسجيل الدخول",
  "hero.eyebrow": "سلسلة المرجع",
  "hero.title": "الصوت، بكل تفاصيله.",
  "hero.subtitle": "أوريك ون",
  "hero.description": "سماعات لاسلكية بمعايير مرجعية مع محركات بيريليوم 40 مم، إلغاء ضوضاء تكيّفي، بطارية 60 ساعة، وصوت Hi-Res فائق.",
  "hero.cta.shop": "تسوق أوريك ون",
  "hero.cta.reviews": "اقرأ التقييمات",
  "hero.cta.explore": "اكتشف الصوت",
  "hero.price.from": "من",
  "hero.save": "وفّر 150 دولار",
  "showcase.eyebrow": "هُندست، لم تُجمّع",
  "showcase.title": "ثلاث سنوات في الصنع",
  "showcase.body": "كل سماعة أوريك ون نتاج هندسة لا هوادة فيها — محركات بيريليوم مشغولة بدقة 0.5 ميكرون، مضخم Class-A مخصص، ثمانية ميكروفونات تقرأ بيئتك 50,000 مرة في الثانية.",
  "features.eyebrow": "ما الداخل",
  "features.title": "أربعة أسباب تجعلها تبدو هكذا",
  "features.subtitle": "كل نظام بُني من المبادئ الأولى. لا منصات مستعارة. لا ملفات DSP جاهزة.",
  "specs.eyebrow": "تقني",
  "specs.title": "المواصفات الكاملة",
  "specs.subtitle": "مُقاسة، لا مُقدّرة. كل مواصفة مُتحقَّق منها في كل وحدة تُشحن.",
  "comparison.eyebrow": "كيف تُقارن",
  "comparison.title": "أوريك ون مقابل المنافسين",
  "comparison.subtitle": "المواصفات المهمة جنباً إلى جنب. نرحب بالمقارنة.",
  "comparison.auric": "أوريك ون",
  "comparison.other": "المنافس الرائد",
  "lifestyle.eyebrow": "صُممت للجلسات الطويلة",
  "lifestyle.title": "ثماني ساعات، بلا وزن",
  "lifestyle.body": "عصابة رأس عائمة وكؤوس أذن جلدية بروتينية توزّع الوزن بالتساوي فتختفي الجلسات الطويلة. أوريك ون لا تطلب منك أخذ فترات راحة — تزيل السبب الذي احتجتها.",
  "gallery.eyebrow": "بالتفصيل",
  "gallery.title": "كل زاوية، مدروسة",
  "gallery.subtitle": "ألمنيوم طيران درجة أولى. جلد بروتيني مخيط يدوياً. مشغول بتفاصيل تشعر بها.",
  "reviews.eyebrow": "مشترون موثقون",
  "reviews.title": "ماذا يقول المالكون",
  "reviews.subtitle": "متوسط 4.9 عبر 2,847 تقييم موثق. لا ننتقي — ننشرها جميعاً.",
  "reviews.based": "بناءً على",
  "reviews.reviews": "تقييم",
  "reviews.verified": "مشترٍ موثّق",
  "reviews.helpful": "مفيد",
  "reviews.write": "اكتب تقييماً",
  "reviews.yourName": "اسمك",
  "reviews.yourTitle": "عنوان التقييم",
  "reviews.yourBody": "تقييمك",
  "reviews.rating": "التقييم",
  "reviews.submit": "إرسال التقييم",
  "reviews.submitting": "جاري الإرسال...",
  "reviews.verifiedOnly": "يمكن للمشترين الموثقين فقط ترك التقييمات.",
  "reviews.distribution": "تفصيل التقييمات",
  "reviews.all": "كل التقييمات",
  "reviews.5star": "5 نجوم",
  "reviews.4star": "4 نجوم",
  "reviews.3star": "3 نجوم",
  "reviews.2star": "2 نجوم",
  "reviews.1star": "نجمة واحدة",
  "reviews.withPhotos": "مع صور",
  "reviews.mostHelpful": "الأكثر فائدة",
  "reviews.mostRecent": "الأحدث",
  "reviews.highestRated": "الأعلى تقييماً",
  "reviews.lowestRated": "الأدنى تقييماً",
  "reviews.sortBy": "ترتيب حسب",
  "reviews.filterBy": "تصفية حسب",
  "reviews.helpfulCount": "وجد هذا مفيداً",
  "testimonials.eyebrow": "موثوق من المحترفين",
  "testimonials.title": "عندما تصبح الغرفة استوديو",
  "testimonials.subtitle": "مهندسو الماسترينغ والمنتجون والملحنون الذين وضعوا أوريك ون في استخدامهم اليومي.",
  "faq.eyebrow": "أسئلة شائعة",
  "faq.title": "كل ما تريد معرفته",
  "faq.subtitle": "لا تجد ما تبحث عنه؟ فريقنا يرد خلال 4 ساعات.",
  "faq.contact": "تواصل مع الدعم",
  "newsletter.eyebrow": "ابق على اطلاع",
  "newsletter.title": "أول استماع لما هو قادم",
  "newsletter.subtitle": "إطلاقات المنتجات، تحديثات البرامج، وأحياناً تعمق هندسي. لا رسائل مزعجة أبداً. إلغاء الاشتراك بنقرة.",
  "newsletter.placeholder": "your@email.com",
  "newsletter.subscribe": "اشترك",
  "newsletter.privacy": "نحترم خصوصيتك. اقرأ سياسة الخصوصية.",
  "trust.shipping": "شحن عالمي مجاني",
  "trust.returns": "إرجاع خلال 30 يوماً",
  "trust.warranty": "ضمان سنتان",
  "trust.secure": "دفع آمن",
  "product.inStock": "متوفر",
  "product.lowStock": "بقي {n} فقط",
  "product.outOfStock": "غير متوفر",
  "product.color": "اللون",
  "product.quantity": "الكمية",
  "product.addToCart": "أضف إلى السلة",
  "product.buyNow": "اشتري الآن",
  "product.estimatedDelivery": "التوصيل المتوقع",
  "product.deliveryValue": "26 – 28 يونيو",
  "product.shippingValue": "مجاني عالمياً",
  "product.warranty": "الضمان",
  "product.warrantyValue": "سنتان",
  "product.returns": "الإرجاع",
  "product.returnsValue": "30 يوماً، إرجاع مجاني",
  "product.share": "مشاركة",
  "product.compare": "قارن",
  "product.wishlist": "أضف للمفضلة",
  "product.specifications": "المواصفات",
  "product.inTheBox": "في العلبة",
  "product.description": "الوصف",
  "product.reviews": "التقييمات",
  "product.related": "قد يعجبك أيضاً",
  "product.accessories": "الملحقات",
  "product.fbt": "يُشترى معاً غالباً",
  "product.fbtSave": "وفّر {n} عند الشراء معاً",
  "product.recentlyViewed": "شوهدت مؤخراً",
  "product.addBundle": "أضف الحزمة للسلة",
  "product.totalBundle": "إجمالي الحزمة",
  "product.features": "الميزات",
  "product.gallery": "المعرض",
  "product.zoom": "مرّر للتكبير. اضغط للتوسيع.",
  "product.expand": "توسيع",
  "product.fullscreen": "عرض كامل الشاشة",
  "product.downloadSpecSheet": "تحميل المواصفات (PDF)",
  "product.downloadManual": "تحميل الدليل (PDF)",
  "product.included": "ما المتضمن",
  "product.cable": "كابل USB-C إلى USB-C (1م)",
  "product.case": "علبة سفر فاخرة",
  "product.adapter": "محول 3.5mm إلى USB-C",
  "product.manual": "دليل البدء السريع",
  "cart.title": "سلتك",
  "cart.empty": "سلتك فارغة",
  "cart.emptySubtitle": "عندما تجد ما تحب، سيظهر هنا.",
  "cart.continueShopping": "متابعة التسوق",
  "cart.subtotal": "المجموع الفرعي",
  "cart.estimatedShipping": "الشحن المقدر",
  "cart.free": "مجاني",
  "cart.estimatedTax": "الضريبة المقدرة",
  "cart.total": "الإجمالي",
  "cart.checkout": "إتمام الشراء",
  "cart.coupon": "رمز الخصم",
  "cart.apply": "تطبيق",
  "cart.couponApplied": "تم تطبيق الخصم",
  "cart.couponInvalid": "رمز غير صالح",
  "cart.giftWrap": "إضافة تغليف هدية (+9 دولار)",
  "cart.giftWrapAdded": "تمت إضافة التغليف",
  "cart.orderNotes": "ملاحظات الطلب",
  "cart.orderNotesPlaceholder": "تعليمات خاصة للبائع...",
  "cart.saveForLater": "احفظ لاحقاً",
  "cart.remove": "إزالة",
  "cart.move": "نقل للسلة",
  "cart.qty": "الكمية",
  "cart.recommendations": "قد يعجبك أيضاً",
  "cart.shippingCalculator": "حاسبة الشحن",
  "cart.calculate": "احسب",
  "cart.zip": "الرمز البريدي",
  "cart.country": "الدولة",
  "cart.empty.look": "تصفح",
  "cart.saved": "محفوظ لاحقاً",
  "cart.savedEmpty": "لا عناصر محفوظة بعد",
  "cart.savedCount": "{n} عناصر محفوظة",
  "cart.youMightLike": "قد يعجبك هذه",
  "cart.freeShipProgress": "أنت على بُعد {n} من الشحن المجاني",
  "cart.freeShipUnlocked": "حصلت على شحن مجاني",
  "cart.freeShipThreshold": "شحن مجاني عند 200 دولار",
  "cartDrawer.title": "حقيبتك",
  "cartDrawer.added": "أُضيف لحقيبتك",
  "cartDrawer.checkout": "إتمام الشراء",
  "cartDrawer.viewCart": "عرض السلة كاملة",
  "cartDrawer.empty": "حقيبتك فارغة",
  "cartDrawer.emptySubtitle": "ابدأ بأوريك ون.",
  "cartDrawer.subtotal": "المجموع الفرعي",
  "cartDrawer.shippingNote": "يُحسب الشحن والضرائب عند الدفع",
  "checkout.title": "إتمام الشراء",
  "checkout.step.shipping": "الشحن",
  "checkout.step.billing": "الفوترة",
  "checkout.step.payment": "الدفع",
  "checkout.step.review": "المراجعة",
  "checkout.contact": "معلومات التواصل",
  "checkout.email": "البريد الإلكتروني",
  "checkout.phone": "رقم الهاتف",
  "checkout.shippingAddress": "عنوان الشحن",
  "checkout.firstName": "الاسم الأول",
  "checkout.lastName": "اسم العائلة",
  "checkout.address1": "العنوان 1",
  "checkout.address2": "العنوان 2 (اختياري)",
  "checkout.city": "المدينة",
  "checkout.state": "الولاية / المحافظة",
  "checkout.postal": "الرمز البريدي",
  "checkout.country": "الدولة",
  "checkout.shippingMethod": "طريقة الشحن",
  "checkout.shipping.standard": "عادي — 2-5 أيام",
  "checkout.shipping.express": "سريع — 1-2 يوم",
  "checkout.shipping.standardPrice": "مجاني",
  "checkout.shipping.expressPrice": "24 دولار",
  "checkout.billingSame": "عنوان الفوترة نفسه عنوان الشحن",
  "checkout.billingAddress": "عنوان الفوترة",
  "checkout.paymentMethod": "طريقة الدفع",
  "checkout.payment.card": "بطاقة ائتمان / خصم",
  "checkout.payment.paypal": "باي بال",
  "checkout.payment.applePay": "أبل باي",
  "checkout.payment.klarna": "كلارنا — 4 دفعات بدون فائدة",
  "checkout.cardNumber": "رقم البطاقة",
  "checkout.cardName": "الاسم على البطاقة",
  "checkout.cardExpiry": "شهر / سنة",
  "checkout.cardCvc": "CVC",
  "checkout.review.order": "مراجعة الطلب",
  "checkout.review.items": "{n} عناصر",
  "checkout.review.placeOrder": "تأكيد الطلب",
  "checkout.processing": "جاري معالجة الدفع...",
  "checkout.securePayment": "دفع آمن ومشفّر",
  "checkout.summary": "ملخص الطلب",
  "checkout.continue": "متابعة",
  "checkout.back": "رجوع",
  "checkout.applyCoupon": "تطبيق الخصم",
  "checkout.coupon": "رمز الخصم",
  "checkout.orderNotes": "ملاحظات الطلب (اختياري)",
  "checkout.giftWrap": "إضافة تغليف هدية",
  "checkout.subscribeMarketing": "أرسل لي إعلانات أوريك",
  "checkout.terms": "أوافق على شروط الخدمة وسياسة الخصوصية",
  "orderSuccess.title": "تم تأكيد الطلب",
  "orderSuccess.body": "شكراً. سماعة أوريك ون في طريقها. أرسلنا تأكيداً ورابط تتبع إلى {email}.",
  "orderSuccess.orderNumber": "رقم الطلب",
  "orderSuccess.trackOrder": "تتبع طلبك",
  "orderSuccess.continueShopping": "متابعة التسوق",
  "orderSuccess.estimatedDelivery": "التوصيل المتوقع",
  "orderSuccess.nowVerified": "أنت الآن مشترٍ موثّق — يمكنك ترك التقييمات!",
  "orderFailed.title": "فشل الدفع",
  "orderFailed.body": "تعذّر معالجة الدفع. لم تُخصم أي رسوم. حاول مرة أخرى أو استخدم طريقة دفع أخرى.",
  "orderFailed.retry": "حاول مرة أخرى",
  "orderFailed.contact": "تواصل مع الدعم",
  "orderCancelled.title": "تم إلغاء الطلب",
  "orderCancelled.body": "تم إلغاء طلبك. لم تُخصم أي رسوم.",
  "orderCancelled.continue": "متابعة التسوق",
  "track.title": "تتبع طلبك",
  "track.subtitle": "أدخل رقم طلبك والبريد المستخدم عند الدفع.",
  "track.orderNumber": "رقم الطلب",
  "track.email": "البريد الإلكتروني",
  "track.track": "تتبع",
  "track.found": "تم العثور على الطلب",
  "track.notFound": "لم يُعثر على الطلب. تحقق من بياناتك.",
  "track.status": "الحالة",
  "track.estimatedDelivery": "التوصيل المتوقع",
  "track.carrier": "الناقل",
  "track.timeline": "الجدول الزمني للشحن",
  "wishlist.title": "مفضلتك",
  "wishlist.subtitle": "العناصر التي حفظتها لاحقاً",
  "wishlist.empty": "مفضلتك فارغة",
  "wishlist.emptySubtitle": "اضغط على القلب على أي منتج لحفظه هنا.",
  "wishlist.moveToCart": "نقل للسلة",
  "wishlist.count": "{n} عناصر",
  "compare.title": "قارن المنتجات",
  "compare.subtitle": "مقارنة جانبية لـ {n} منتجات",
  "compare.empty": "لا شيء للمقارنة بعد",
  "compare.emptySubtitle": "أضف منتجات للمقارنة باستخدام أيقونة المقارنة.",
  "compare.add": "أضف للمقارنة",
  "compare.remove": "إزالة",
  "compare.maxReached": "يمكن مقارنة 4 منتجات كحد أقصى",
  "compare.addToCart": "أضف للسلة",
  "search.title": "بحث",
  "search.placeholder": "ابحث في أوريك...",
  "search.trending": "عمليات بحث رائجة",
  "search.recent": "عمليات بحث حديثة",
  "search.popular": "فئات شائعة",
  "search.results": "نتائج البحث عن \"{q}\"",
  "search.noResults": "لا نتائج لـ \"{q}\"",
  "search.noResultsSubtitle": "جرب كلمات مختلفة أو تصفح منتجاتنا.",
  "search.clear": "مسح",
  "search.clearAll": "مسح الكل",
  "search.count": "{n} نتائج",
  "search.viewAll": "عرض كل النتائج",
  "search.suggestions": "اقتراحات",
  "search.filters": "تصفية",
  "search.sortBy": "ترتيب حسب",
  "search.sort.relevance": "الصلة",
  "search.sort.priceAsc": "السعر: من الأقل للأعلى",
  "search.sort.priceDesc": "السعر: من الأعلى للأقل",
  "search.sort.rating": "الأعلى تقييماً",
  "search.sort.newest": "الأحدث",
  "account.title": "حسابي",
  "account.welcome": "مرحباً بعودتك، {name}",
  "account.recentOrders": "الطلبات الأخيرة",
  "account.viewAll": "عرض الكل",
  "account.noOrders": "لا طلبات بعد",
  "account.noOrdersSubtitle": "عندما تضع طلباً، سيظهر هنا.",
  "account.savedAddresses": "العناوين المحفوظة",
  "account.defaultAddress": "افتراضي",
  "account.addAddress": "أضف عنواناً",
  "account.editAddress": "تعديل",
  "account.paymentMethods": "طرق الدفع",
  "account.addPayment": "أضف طريقة دفع",
  "account.default": "افتراضي",
  "account.profile": "الملف الشخصي",
  "account.profile.firstName": "الاسم الأول",
  "account.profile.lastName": "اسم العائلة",
  "account.profile.email": "البريد الإلكتروني",
  "account.profile.phone": "الهاتف",
  "account.profile.save": "حفظ التغييرات",
  "account.security": "الأمان",
  "account.security.password": "كلمة المرور",
  "account.security.changePassword": "تغيير كلمة المرور",
  "account.security.currentPassword": "كلمة المرور الحالية",
  "account.security.newPassword": "كلمة المرور الجديدة",
  "account.security.confirmPassword": "تأكيد كلمة المرور",
  "account.security.twoFactor": "المصادقة الثنائية",
  "account.security.twoFactorDesc": "أضف طبقة أمان إضافية مع TOTP",
  "account.security.sessions": "الجلسات النشطة",
  "account.security.signOutAll": "تسجيل الخروج من كل الجلسات",
  "account.notifications": "الإشعارات",
  "account.notif.orders": "تحديثات الطلبات",
  "account.notif.marketing": "إطلاقات المنتجات",
  "account.notif.reviews": "ردود التقييمات",
  "account.notif.security": "تنبيهات الأمان",
  "account.signout": "تسجيل الخروج",
  "account.orderId": "الطلب",
  "account.orderDate": "التاريخ",
  "account.orderStatus": "الحالة",
  "account.orderTotal": "الإجمالي",
  "account.orderActions": "إجراءات",
  "account.viewOrder": "عرض",
  "account.invoice": "الفاتورة",
  "account.buyAgain": "اشتر مرة أخرى",
  "account.track": "تتبع",
  "account.return": "إرجاع",
  "account.cancelOrder": "إلغاء",
  "account.status.delivered": "تم التسليم",
  "account.status.shipped": "تم الشحن",
  "account.status.processing": "قيد المعالجة",
  "account.status.cancelled": "ملغي",
  "account.status.returned": "مُرتجع",
  "invoice.title": "فاتورة",
  "invoice.number": "رقم الفاتورة",
  "invoice.date": "تاريخ الفاتورة",
  "invoice.due": "تاريخ الاستحقاق",
  "invoice.billTo": "فاتورة إلى",
  "invoice.shipTo": "شحن إلى",
  "invoice.item": "العنصر",
  "invoice.qty": "الكمية",
  "invoice.price": "السعر",
  "invoice.total": "الإجمالي",
  "invoice.subtotal": "المجموع الفرعي",
  "invoice.shipping": "الشحن",
  "invoice.tax": "الضريبة",
  "invoice.grandTotal": "الإجمالي الكلي",
  "invoice.download": "تحميل PDF",
  "invoice.print": "طباعة",
  "invoice.thanks": "شكراً لتعاملكم معنا.",
  "auth.signIn": "تسجيل الدخول",
  "auth.signUp": "إنشاء حساب",
  "auth.forgot": "نسيت كلمة المرور؟",
  "auth.reset": "إعادة تعيين كلمة المرور",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.confirmPassword": "تأكيد كلمة المرور",
  "auth.name": "الاسم الكامل",
  "auth.signInButton": "تسجيل الدخول",
  "auth.signUpButton": "إنشاء حساب",
  "auth.resetButton": "إرسال رابط إعادة التعيين",
  "auth.resetSent": "إذا كان هناك حساب لـ {email}، فقد أُرسل رابط إعادة التعيين.",
  "auth.noAccount": "ليس لديك حساب؟",
  "auth.haveAccount": "لديك حساب بالفعل؟",
  "auth.signInWith": "أو تابع باستخدام",
  "auth.terms": "بإنشاء حساب، فإنك توافق على الشروط وسياسة الخصوصية.",
  "auth.welcomeBack": "مرحباً بعودتك",
  "auth.createAccount": "انضم إلى أوريك",
  "auth.createAccountSubtitle": "دفع أسرع، سجل الطلبات، وإطلاقات حصرية.",
  "auth.signInSubtitle": "سجّل الدخول إلى حساب أوريك",
  "auth.forgotSubtitle": "أدخل بريدك وسنرسل رابط إعادة التعيين.",
  "auth.resetSubtitle": "أدخل كلمة المرور الجديدة",
  "auth.newPassword": "كلمة المرور الجديدة",
  "auth.updatePassword": "تحديث كلمة المرور",
  "auth.passwordUpdated": "تم تحديث كلمة المرور. يمكنك الآن تسجيل الدخول.",
  "auth.rememberMe": "تذكرني",
  "policy.shipping": "سياسة الشحن",
  "policy.returns": "الإرجاع والاستبدال",
  "policy.warranty": "الضمان",
  "policy.privacy": "سياسة الخصوصية",
  "policy.terms": "شروط الخدمة",
  "policy.refund": "سياسة الاسترداد",
  "policy.lastUpdated": "آخر تحديث",
  "policy.tableOfContents": "في هذه الصفحة",
  "about.eyebrow": "قصتنا",
  "about.title": "بدأنا في ورشة كوبنهاغن",
  "about.subtitle": "تأسست أوريك عام 2021 على يد ثلاثة مهندسين سابقين من بانغ آند أولوفسن الذين آمنوا أن الصوت اللاسلكي لم يصل لذاته.",
  "about.founded": "تأسست",
  "about.headquarters": "المقر",
  "about.team": "الفريق",
  "about.mission": "المهمة",
  "about.vision": "الرؤية",
  "about.cta": "اكتشف أوريك ون",
  "contact.title": "تواصل معنا",
  "contact.subtitle": "يرد فريقنا خلال 4 ساعات، من الإثنين للجمعة.",
  "contact.name": "اسمك",
  "contact.email": "بريدك الإلكتروني",
  "contact.subject": "الموضوع",
  "contact.message": "الرسالة",
  "contact.send": "إرسال",
  "contact.sent": "تم إرسال الرسالة. سنرد خلال 4 ساعات.",
  "contact.emailUs": "راسلنا",
  "contact.callUs": "اتصل بنا",
  "contact.hours": "ساعات العمل",
  "contact.visitUs": "زرنا",
  "support.title": "مركز المساعدة",
  "support.subtitle": "اعثر على إجابات، تصفح المقالات، أو تواصل مع فريقنا.",
  "support.search": "ابحث في مقالات المساعدة...",
  "support.browse": "تصفح حسب الفئة",
  "support.popular": "مقالات شائعة",
  "support.contactSupport": "تواصل مع الدعم",
  "support.openTicket": "افتح تذكرة دعم",
  "support.ticketSubject": "الموضوع",
  "support.ticketOrder": "رقم الطلب (اختياري)",
  "support.ticketCategory": "الفئة",
  "support.ticketPriority": "الأولوية",
  "support.ticketMessage": "صف مشكلتك",
  "support.ticketSubmit": "إرسال التذكرة",
  "support.ticketSubmitted": "تم إنشاء التذكرة #{n}. سنرد خلال 4 ساعات.",
  "error.404.title": "الصفحة غير موجودة",
  "error.404.body": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
  "error.500.title": "حدث خطأ ما",
  "error.500.body": "نحن نعمل عليه. حاول مرة أخرى بعد لحظة.",
  "error.offline.title": "أنت غير متصل",
  "error.offline.body": "تحقق من اتصالك وحاول مرة أخرى.",
  "error.maintenance.title": "سنعود قريباً",
  "error.maintenance.body": "أوريك تحت صيانة مجدولة. عودة قريبة.",
  "error.comingSoon.title": "قريباً",
  "error.comingSoon.body": "شيء جديد في الطريق. كن أول من يعرف.",
  "error.retry": "حاول مرة أخرى",
  "error.home": "العودة للرئيسية",
  "footer.tagline": "صوت مُكرّر. صُنع في كوبنهاغن.",
  "footer.shop": "تسوق",
  "footer.company": "الشركة",
  "footer.help": "المساعدة",
  "footer.follow": "تابعنا",
  "footer.subscribe": "اشترك",
  "footer.subscribeBody": "أول استماع لما هو قادم. لا رسائل مزعجة.",
  "footer.rights": "جميع الحقوق محفوظة.",
  "footer.terms": "الشروط",
  "footer.privacy": "الخصوصية",
  "footer.cookies": "ملفات تعريف الارتباط",
  "footer.accessibility": "إمكانية الوصول",
  "footer.poweredBy": "هُندست في كوبنهاغن، تُشحن عالمياً.",
  "common.loading": "جاري التحميل...",
  "common.saving": "جاري الحفظ...",
  "common.cancel": "إلغاء",
  "common.save": "حفظ",
  "common.delete": "حذف",
  "common.edit": "تعديل",
  "common.close": "إغلاق",
  "common.continue": "متابعة",
  "common.back": "رجوع",
  "common.next": "التالي",
  "common.previous": "السابق",
  "common.apply": "تطبيق",
  "common.search": "بحث",
  "common.filter": "تصفية",
  "common.sort": "ترتيب",
  "common.viewAll": "عرض الكل",
  "common.viewMore": "عرض المزيد",
  "common.viewLess": "عرض أقل",
  "common.addToCart": "أضف للسلة",
  "common.buyNow": "اشتري الآن",
  "common.outOfStock": "غير متوفر",
  "common.inStock": "متوفر",
  "common.new": "جديد",
  "common.sale": "تخفيض",
  "common.bestseller": "الأكثر مبيعاً",
  "common.limited": "محدود",
  "common.free": "مجاني",
  "common.optional": "اختياري",
  "common.required": "مطلوب",
  "common.currency": "$",
  "common.select": "اختر...",
  "common.yes": "نعم",
  "common.no": "لا",
  "common.copied": "تم النسخ!",
  "common.share": "مشاركة",
};

const dictionaries: Record<Language, Dict> = { en, ar };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("auric-language") as Language | null;
      if (saved && (saved === "en" || saved === "ar")) {
        setLanguageState(saved);
      }
    }
  }, []);

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("auric-language", language);
      document.documentElement.lang = language;
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    }
  }, [language]);

  const setLanguage = useCallback((lang: Language) => setLanguageState(lang), []);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      let str = dictionaries[language][key] ?? key;
      if (vars) {
        for (const [k, v] of Object.entries(vars)) {
          str = str.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
        }
      }
      return str;
    },
    [language],
  );

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
